//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.04 at 08:28:33 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://course.management.app.com/course-details", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.app.management.course.course_details;
